this["JST"] = this["JST"] || {};

this["JST"]["templates/accept-account-invite-iframe.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div class=\"modal fade\" id=\"accept-account-invite-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"accept-account-invite-modal-label\" aria-hidden=\"true\">\n  <div class=\"modal-dialog\" role=\"document\">\n    <div class=\"modal-content\">\n      <div class=\"modal-header\">\n        <button type=\"button\" class=\"close close-modal\" aria-label=\"Close\">\n          <span aria-hidden=\"true\">&times;</span>\n        </button>\n       <br>\n      </div>\n	  <div class=\"modal-body\">\n      	<iframe class=\"popover-iframe\"></iframe>\n      </div>\n    </div>\n  </div>\n</div>  ";
},"useData":true});

this["JST"]["templates/accept-account-invite-modal.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div class=\"modal-content-x\" id=\"accept-account-invite-modal\">\n   \n<div class=\"modal-body\" id=\"accept-account-invite-form\">\n\n    \n<div class=\"acceptinvite-verify-code-form\">\n  \n    \n<p>Verify Account Invite Code:</p>\n<div class=\"form-group \">\n<input type=\"text\" class=\"account-invite-code form-control modal-active return-aware\" readonly />\n        \n</div>    \n\n<button id=\"account-invite-confirm-button\" class=\"btn btn-primary account-invite-confirm\">Verify Account Invite Code</button>\n    \n<button class=\"btn btn-primary close-modal\">Close</button>\n       \n</div>\n    \n\n    \n<div class=\"new-account-form\" style=\"display: none;\">\n \n<p>Invitation verified, now create your account.</p>\n\n<p>Your password should be at least 8 characters long containing an upper case letter, a lowercase letter, a number, and a special character (like $, @, or !).</p>    \n\n<div class=\"form-group \">\n<input type=\"email\" class=\"input-email form-control modal-active return-aware\" readonly=\"readonly\" placeholder=\"Email Address\"/>\n</div>\n     \n<div class=\"form-group \">\n<input type=\"password\" class=\"input-password form-control modal-active return-aware\" placeholder=\"New Password\" />\n</div>\n    \n<div class=\"form-group \">\n<input type=\"password\" class=\"input-password-repeat form-control modal-active return-aware\" placeholder=\"Repeat Password\" />\n</div>\n\n<div class=\"password-validation-error text-danger\" style=\"\"></div>\n<div class=\"password-validation-error-two text-danger\" style=\"\"></div>\n   \n<div class=\"form-separator\" style=\"\"></div>\n\n<button class=\"create-account-button btn btn-primary button-disabled\" role=\"button\" >Create Account</button>\n    \n</div>\n	\n<div class=\"success-form\" style=\"display: none;\">\n\n<p>Account was successfully created.    \n</p> \n    \n<div class=\"request-success text-success\" style=\"\"></div>\n	    \n<button class=\"btn btn-primary go-to-login\">Go to Login</button>\n    \n<button class=\"btn btn-primary close-modal\">Close</button>\n\n</div>    \n\n\n<div class=\"error-form\" style=\"display: none;\">\n    \n<p>There was an error creating the account.\n</p>\n  \n<div class=\"request-error text-danger\" style=\"\"></div>\n    \n<button class=\"btn btn-primary close-modal\">Close</button>\n  \n</div>\n    \n</div>\n\n</div>\n";
},"useData":true});

this["JST"]["templates/accept-member-invite-iframe.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div class=\"modal fade\" id=\"accept-member-invite-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"accept-member-invite-modal-label\" aria-hidden=\"true\">\n  <div class=\"modal-dialog\" role=\"document\">\n    <div class=\"modal-content\">\n      <div class=\"modal-header\">\n        <button type=\"button\" class=\"close close-modal\" aria-label=\"Close\">\n          <span aria-hidden=\"true\">&times;</span>\n        </button>\n       <br>\n      </div>\n	  <div class=\"modal-body\">\n      	<iframe class=\"popover-iframe\"></iframe>\n      </div>\n    </div>\n  </div>\n</div>  ";
},"useData":true});

this["JST"]["templates/accept-member-invite-modal.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div class=\"modal-content-x\" id=\"accept-member-invite-modal\">\n   \n<div class=\"modal-body\" id=\"accept-member-invite-form\">\n    \n<div class=\"acceptinvite-verify-code-form\">\n    \n<p>Verify Member Invite Code:</p>\n\n<div class=\"form-group \">\n<input type=\"text\" class=\"member-invite-code form-control modal-active return-aware\" readonly/>\n</div>    \n\n<button id=\"member-invite-confirm-button\" class=\"btn btn-primary account-invite-confirm\">Verify Member Invite Code</button>\n    \n<button class=\"btn btn-primary close-modal\">Close</button>\n       \n</div>\n    \n<div class=\"new-member-form\" style=\"display: none;\">\n \n<p>Invitation verified, now create your login.</p>\n\n<p>Your password should be at least 8 characters long containing an upper case letter, a lowercase letter, a number, and a special character (like $, @, or !).</p>    \n\n<!-- bit of a hack to try and get these lined up -->\n<div class=\"row\">\n<div class=\"form-group col-md-12\">\n<label for=\"invitation-source\" class=\"col-form-label col-sm-2\">Invited By:</label>\n<div class=\"flex-item-grow col-sm-10\" style=\"justify-content: flex-end;\">\n<input id=\"invitation-source\" type=\"email\" class=\"invited-input-email form-control modal-active return-aware\"  readonly=\"readonly\" placeholder=\"Invited by Email Address\"/>\n</div>    \n</div>\n</div>\n    \n<div class=\"form-group \">\n<input type=\"email\" class=\"input-email form-control modal-active return-aware\" readonly=\"readonly\" placeholder=\"Email Address\"/>\n</div>\n     \n<div class=\"form-group \">\n<input type=\"password\" class=\"input-password form-control modal-active return-aware\" placeholder=\"New Password\" />\n</div>\n    \n<div class=\"form-group \">\n<input type=\"password\" class=\"input-password-repeat form-control modal-active return-aware\" placeholder=\"Repeat Password\" />\n</div>\n\n<div class=\"password-validation-error text-danger\" style=\"\"></div>\n<div class=\"password-validation-error-two text-danger\" style=\"\"></div>\n   \n<div class=\"form-separator\" style=\"\"></div>\n\n<button class=\"create-member-button btn btn-primary button-disabled\" role=\"button\" >Create Member</button>\n    \n</div>\n	\n<div class=\"success-form\" style=\"display: none;\">\n\n<p>Member was successfully created.    \n</p> \n    \n<div class=\"request-success text-success\" style=\"\"></div>\n	    \n<button class=\"btn btn-primary go-to-login\">Go to Login</button>\n    \n<button class=\"btn btn-primary close-modal\">Close</button>\n\n</div>    \n\n\n<div class=\"error-form\" style=\"display: none;\">\n    \n<p>There was an error creating the login.\n</p>\n  \n<div class=\"request-error text-danger\" style=\"\"></div>\n    \n<button class=\"btn btn-primary close-modal\">Close</button>\n  \n</div>\n    \n</div>\n\n</div>\n\n    \n";
},"useData":true});

this["JST"]["templates/confirm-email-iframe.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "\r\n<div class=\"modal fade\" id=\"confirm-email-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"confirm-email-modal-label\" aria-hidden=\"true\">\r\n  <div class=\"modal-dialog\" role=\"document\">\r\n    <div class=\"modal-content\">\r\n      <div class=\"modal-header\">\r\n        <button type=\"button\" class=\"close close-modal\" aria-label=\"Close\">\r\n          <span aria-hidden=\"true\">&times;</span>\r\n        </button>\r\n       <br>\r\n      </div>\r\n	  <div class=\"modal-body\">\r\n      	<iframe class=\"popover-iframe\"></iframe>\r\n      </div>\r\n    </div>\r\n  </div>\r\n</div>       \r\n  ";
},"useData":true});

this["JST"]["templates/confirm-email-modal.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div class=\"modal-content-x\" id=\"confirm-email-modal\">\r\n    \r\n<div class=\"modal-body\" id=\"confirm-email-form\">\r\n      \r\n<input type=\"hidden\" class=\"input-code\" name=\"input-code\" value=\"\"/>\r\n<input type=\"hidden\" class=\"input-email\" name=\"input-email\" value=\"\"/>\r\n	          \r\n<div class=\"no-input text-danger\" style=\"display: none;\">\r\n<div>No input email or code!</div>\r\n</div>\r\n\r\n<div class=\"input-ok\" style=\"display: none;\">\r\n          \r\n<div class=\"success-hide\">\r\n		          \r\n<p class=\"\">Verifying email...</p>\r\n		          \r\n<br>\r\n		          \r\n<div class=\"text-danger\" style=\"margin-top: 20px;\"><span style=\"display: none;\" class=\"error text-danger\"></span></div>\r\n		  		    \r\n</div>\r\n	          \r\n<div class=\"success text-center\" style=\"display: none;\">\r\n		      \r\n<p class=\"text-success\"></p>\r\n\r\n		      	\r\n<button id=\"confirm-email-button\" class=\"btn btn-primary confirm-email\">Confirm Email</button>\r\n\r\n	     	\r\n<button class=\"btn btn-primary close-modal\">Close</button>\r\n		      	\r\n</div>\r\n          \r\n          \r\n</div>\r\n      \r\n</div>\r\n    \r\n<div class=\"modal-footer\">\r\n<div class=\"success\" style=\"display: none;\">\r\n</div>\r\n    \r\n</div>\r\n</div>\r\n  ";
},"useData":true});

this["JST"]["templates/confirm-login-email-iframe.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "\n<div class=\"modal fade\" id=\"confirm-login-email-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"confirm-login-email-modal-label\" aria-hidden=\"true\">\n  <div class=\"modal-dialog\" role=\"document\">\n    <div class=\"modal-content\">\n      <div class=\"modal-header\">\n        <button type=\"button\" class=\"close close-modal\" aria-label=\"Close\">\n          <span aria-hidden=\"true\">&times;</span>\n        </button>\n       <br>\n      </div>\n	  <div class=\"modal-body\">\n      	<iframe class=\"popover-iframe\"></iframe>\n      </div>\n    </div>\n  </div>\n</div>   ";
},"useData":true});

this["JST"]["templates/confirm-login-email-modal.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div class=\"modal-content-x\" id=\"confirm-login-email-modal\">\n   \n<div class=\"modal-body\" id=\"confirm-login-email-form\">\n \n    \n<div class=\"confirmlogin-verify-code-form\">\n  \n    \n<p>Verify Login Code:</p>\n    \n<div class=\"verify-code-message\" style=\"display: none;\">\n</div>    \n\n<div class=\"form-group \">\n<input type=\"text\" class=\"confirm-login-code form-control modal-active return-aware\" readonly />\n        \n</div>    \n\n<button id=\"confirm-login-email-button\" class=\"btn btn-primary account-invite-confirm\">Verify Code</button>\n    \n<button class=\"btn btn-primary close-modal\">Close</button>\n       \n</div>\n       \n\n<div class=\"unlock-success-form\" style=\"display: none;\">\n\n<p>Login was successfully confirmed and your Login unlocked.\n</p> \n    \n<div class=\"request-success text-success\" style=\"\"></div>\n	    \n<button class=\"btn btn-primary go-to-login\">Go to Login</button>\n    \n<button class=\"btn btn-primary close-modal\">Close</button>\n\n</div>\n\n<div class=\"unlock-error-form\" style=\"display: none;\">\n    \n<p>There was an error confirming the login code.\n</p>\n  \n<div class=\"request-error text-danger\" style=\"\"></div>\n    \n<button class=\"btn btn-primary close-modal\">Close</button>\n  \n</div>\n\n    \n    \n<div class=\"changelogin-success-form\" style=\"display: none;\">\n\n<p>Login was successfully confirmed and your Login changed.\n</p> \n    \n<div class=\"change-login-old-login\" style=\"\"></div>\n	    \n<div class=\"change-login-new-login\" style=\"\"></div>\n  \n<div class=\"request-success text-success\" style=\"\"></div>\n      \n<button class=\"btn btn-primary go-to-login\">Go to Login</button>\n    \n<button class=\"btn btn-primary close-modal\">Close</button>\n\n</div>\n\n<div class=\"changelogin-error-form\" style=\"display: none;\">\n    \n<p>There was an error confirming the login code.  Your login was not changed.\n</p>\n  \n<div class=\"request-error text-danger\" style=\"\"></div>\n    \n<button class=\"btn btn-primary close-modal\">Close</button>\n  \n</div>  \n    \n    \n    \n    \n    \n</div>\n";
},"useData":true});

this["JST"]["templates/header.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!-- header-1 -->\n        <header class=\"header-1\">\n            <div class=\"container\">\n                <div class=\"row\">\n                    <div class=\"navbar col-sm-12 navbar-fixed-top\" role=\"navigation\">\n                        <div class=\"navbar-header\">\n                            <button type=\"button\" class=\"navbar-toggle\"></button>\n                            <a class=\"brand\" href=\"#home\"><img src=\"img/haleylogo_offwhite_normal.png\" style=\"height: 50px;\" alt=\"\"></a>\n                        </div>\n                        <div class=\"navbar-collapse collapse\">\n                            <ul class=\"nav pull-left\">\n                                <li>\n                                    <a href=\"index.html\">HOME</a>\n			      </li>\n\n\n                                <li>\n                                    <a href=\"index.html/#contact\">CONTACT</a>\n                                </li>\n                                \n                            </ul>\n                               <ul class=\"nav pull-right\"> \n                                <li><br>\n<button type=\"button\" class=\"btn btn-info btn-md\" data-toggle=\"#\" data-target=\"#\">\nLOG IN\n</button>\n                                </li>\n                                <li><br>\n<button type=\"button\" class=\"btn btn-primary btn-md\" data-toggle=\"modal\" data-target=\"#myModal\">\nSIGN UP\n</button>\n                                </li>\n                            </ul>\n                            <ul class=\"subnav\">\n               \n                            </ul>\n                        </div>\n                    </div>\n                </div>\n            </div>\n        </header>";
},"useData":true});

this["JST"]["templates/login-iframe.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!-- Modal -->\r\n<div class=\"modal fade\" id=\"login-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"login-modal-label\" aria-hidden=\"true\">\r\n  <div class=\"modal-dialog\" role=\"document\">\r\n    <div class=\"modal-content\" id=\"login-form\">\r\n      <div class=\"modal-header\">\r\n        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n          <span aria-hidden=\"true\">&times;</span>\r\n        </button>\r\n       <br>\r\n      </div>\r\n      <div class=\"modal-body\">\r\n      	<iframe class=\"popover-iframe\"></iframe>\r\n      </div>\r\n    </div>\r\n  </div>\r\n</div>\r\n";
},"useData":true});

this["JST"]["templates/login-modal.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<script>\r\n  function forceLowerCase(input) {\r\n    input.value = input.value.toLowerCase();\r\n  }\r\n</script>\r\n\r\n    <div class=\"modal-content-x\" id=\"login-form\">\r\n   	  \r\n      <div class=\"modal-body\">\r\n \r\n     <div class=\"text-center\">\r\n     	\r\n     	<span style=\"font-size: 24px;\" class=\"logo-lg\">Chat AI</span>\r\n     </div>\r\n     <div class=\"form-group \">\r\n        <label>Username:</label>\r\n       <input type=\"text\" class=\"form-control return-aware modal-active\" placeholder=\"Username\" id=\"UserName\" oninput=\"forceLowerCase(this)\">\r\n       <i class=\"fa fa-user\"></i>\r\n     </div>\r\n     <div class=\"form-group log-status\">\r\n        <label>Password:</label>\r\n       <input type=\"password\" class=\"form-control return-aware modal-active\" placeholder=\"Password\" id=\"Password\">\r\n       <i class=\"fa fa-lock\"></i>\r\n     </div>\r\n          \r\n    \r\n          \r\n      <div><a href=\"/resetpassword\" data-navigo2>Forgot password?</a></div>\r\n      \r\n      <div><a href=\"/unlocklogin\" data-navigo2>Locked login?</a></div>\r\n      \r\n          \r\n      <div>&nbsp;<span class=\"status login-error text-danger\"></span><span class=\"status login-success text-success\"></span></div>\r\n      \r\n      </div>\r\n      <div class=\"modal-footer\">\r\n        <div class=\"text-center\">\r\n        	<button id=\"login-button\" type=\"button\" class=\"btn btn-info modal-active\">Log In</button><br><br>\r\n        	\r\n        	<a href=\"/signup\" data-navigo2>Join Waiting List</a>\r\n        </div>\r\n      </div>\r\n    </div>";
},"useData":true});

this["JST"]["templates/password-reset-confirm-iframe.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "\r\n<div class=\"modal fade\" id=\"password-reset-confirm-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"password-reset-confirm-modal-label\" aria-hidden=\"true\">\r\n  <div class=\"modal-dialog\" role=\"document\">\r\n    <div class=\"modal-content\">\r\n      <div class=\"modal-header\">\r\n        <button type=\"button\" class=\"close close-modal\" aria-label=\"Close\">\r\n          <span aria-hidden=\"true\">&times;</span>\r\n        </button>\r\n       <br>\r\n      </div>\r\n	  <div class=\"modal-body\">\r\n      	<iframe class=\"popover-iframe\"></iframe>\r\n      </div>\r\n    </div>\r\n  </div>\r\n</div>       \r\n  ";
},"useData":true});

this["JST"]["templates/password-reset-confirm-modal.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "\r\n<div class=\"modal-content-x\" id=\"password-reset-confirm-modal\">\r\n    \r\n<div class=\"modal-body\">\r\n   \r\n<div class=\"confirmation-code-form\">\r\n    \r\n<p>Reset Password Confirmation Code:</p>\r\n<div class=\"form-group \">\r\n<input type=\"text\" class=\"reset-confirmation-code form-control modal-active return-aware\" readonly />\r\n</div>    \r\n\r\n\r\n<button id=\"password-reset-confirm-button\" class=\"btn btn-primary password-reset-confirm\">Verify Confirmation Code</button>\r\n    \r\n<button class=\"btn btn-primary close-modal\">Close</button>\r\n    \r\n</div>    \r\n    \r\n<div class=\"new-password-form\" style=\"display: none;\">\r\n \r\n<p>Confirmation code verified, now reset your password.</p>\r\n\r\n<p>Your password should be at least 8 characters long containing an upper case letter, a lowercase letter, a number, and a special character (like $, @, or !).</p>    \r\n\r\n<div class=\"form-group \">\r\n<input type=\"email\" class=\"input-email form-control modal-active return-aware\" readonly=\"readonly\" placeholder=\"Email Address\"/>\r\n</div>\r\n     \r\n<div class=\"form-group \">\r\n<input type=\"password\" class=\"input-password form-control modal-active return-aware\" placeholder=\"New Password\" />\r\n</div>\r\n    \r\n<div class=\"form-group \">\r\n<input type=\"password\" class=\"input-password-repeat form-control modal-active return-aware\" placeholder=\"Repeat Password\" />\r\n</div>\r\n\r\n<div class=\"password-validation-error text-danger\" style=\"\"></div>\r\n<div class=\"password-validation-error-two text-danger\" style=\"\"></div>\r\n   \r\n<div class=\"form-separator\" style=\"\"></div>\r\n\r\n<button class=\"email-reset-button btn btn-primary button-disabled\" role=\"button\" >Reset Password</button>\r\n    \r\n</div>\r\n	\r\n<div class=\"success-form\" style=\"display: none;\">\r\n\r\n<p>Password was successfully reset.    \r\n</p> \r\n    \r\n<div class=\"request-success text-success\" style=\"\"></div>\r\n	    \r\n<button class=\"btn btn-primary go-to-login\">Go to Login</button>\r\n    \r\n<button class=\"btn btn-primary close-modal\">Close</button>\r\n\r\n</div>    \r\n\r\n\r\n<div class=\"error-form\" style=\"display: none;\">\r\n    <p>There was an error resetting the password.</p>    \r\n  \r\n<div class=\"request-error text-danger\" style=\"\"></div>\r\n    \r\n<button class=\"btn btn-primary close-modal\">Close</button>\r\n  \r\n</div>\r\n    \r\n</div>\r\n\r\n</div>\r\n";
},"useData":true});

this["JST"]["templates/request-invitation-iframe.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!-- Request invitation modal -->\r\n<div class=\"modal fade\" id=\"request-invitation-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"request-invitation-modal-label\" aria-hidden=\"true\">\r\n  <div class=\"modal-dialog\" role=\"document\">\r\n    <div class=\"modal-content\">\r\n      <div class=\"modal-header\">\r\n        <button type=\"button\" class=\"close close-modal\" aria-label=\"Close\">\r\n          <span aria-hidden=\"true\">&times;</span>\r\n        </button>\r\n       <br>\r\n      </div>\r\n      <div class=\"modal-body\">\r\n      	<iframe class=\"popover-iframe\"></iframe>\r\n      </div>		\r\n    </div>\r\n  </div>\r\n</div>   ";
},"useData":true});

this["JST"]["templates/request-invitation-modal.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!-- Request invitation modal -->\r\n<!-- \r\n<div class=\"modal fade\" id=\"request-invitation-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"request-invitation-modal-label\" aria-hidden=\"true\">\r\n  <div class=\"modal-dialog\" role=\"document\">\r\n -->\r\n    <div class=\"modal-content-x\" id=\"request-invitation-modal\">\r\n    <!-- \r\n      <div class=\"modal-header\">\r\n        <button type=\"button\" class=\"close close-modal\" aria-label=\"Close\">\r\n          <span aria-hidden=\"true\">&times;</span>\r\n        </button>\r\n       <br>\r\n      </div>\r\n     -->\r\n      <div class=\"modal-body\">\r\n      \r\n      	<div class=\"initial\">\r\n      \r\n			<p>Email Address:</p>\r\n	     	<div class=\"form-group \">\r\n	       		<input type=\"text\" class=\"form-control invitation-active\" placeholder=\"Email\" id=\"invitation-code-email\">\r\n	       		<i class=\"fa fa-user\"></i>\r\n	     	</div>\r\n	     	\r\n	     	<div>&nbsp;\r\n				<span class=\"invitation-error invitation-status text-danger\"></span>\r\n				<!-- <span class=\"invitation-success invitation-status text-success\" style=\"color:green;\"></span>-->\r\n	     	</div>\r\n	     	\r\n      	</div>\r\n      	\r\n      	<div class=\"on-success text-center\" style=\"display: none;\">\r\n      		<br><br><p>Thank you for your interest in Chat AI, you will receive an email from us shortly.</p>\r\n      	</div>\r\n      	\r\n      </div>\r\n      <div class=\"modal-footer\">\r\n      \r\n        <div class=\"initial text-center\">\r\n        	<button class=\"btn btn-info invitation-active\" role=\"button\" id=\"request-invitation-code-button\">Request</button>\r\n        </div>\r\n\r\n	        \r\n        <div class=\"on-success text-center\" style=\"display: none;\">\r\n        	<button class=\"btn btn-info close-modal\" role=\"button\">Close</button>\r\n        </div>\r\n		\r\n      </div>\r\n    </div>\r\n<!-- \r\n  </div>\r\n</div>   \r\n -->";
},"useData":true});

this["JST"]["templates/reset-password-iframe.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "\r\n<div class=\"modal fade\" id=\"reset-password-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"reset-password-modal-label\" aria-hidden=\"true\">\r\n  <div class=\"modal-dialog\" role=\"document\">\r\n    <div class=\"modal-content\">\r\n      <div class=\"modal-header\">\r\n        <button type=\"button\" class=\"close close-modal\" aria-label=\"Close\">\r\n          <span aria-hidden=\"true\">&times;</span>\r\n        </button>\r\n       <br>\r\n      </div>\r\n	  <div class=\"modal-body\">\r\n      	<iframe class=\"popover-iframe\"></iframe>\r\n      </div>\r\n    </div>\r\n  </div>\r\n</div>       ";
},"useData":true});

this["JST"]["templates/reset-password-modal.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!-- \r\n<div class=\"modal fade\" id=\"reset-password-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"reset-password-modal-label\" aria-hidden=\"true\">\r\n  <div class=\"modal-dialog\" role=\"document\">\r\n -->\r\n    <div class=\"modal-content-x\" id=\"reset-password-modal\">\r\n      <!--\r\n      <div class=\"modal-header\">\r\n        <button type=\"button\" class=\"close close-modal\" aria-label=\"Close\">\r\n          <span aria-hidden=\"true\">&times;</span>\r\n        </button>\r\n       <br>\r\n      </div>\r\n      -->\r\n      <div class=\"modal-body\">\r\n      \r\n      	<div class=\"initial\">\r\n      \r\n            <p>Request resetting your Chat.AI Password:</p>\r\n            \r\n        	<p>Email Address:</p>\r\n     		<div class=\"form-group \">\r\n       			<input type=\"email\" class=\"form-control modal-active\" placeholder=\"Email\" id=\"reset-input-email\">\r\n       			<i class=\"fa fa-user\"></i>\r\n     		</div>\r\n     		\r\n     		<div>&nbsp;\r\n				<span class=\"request-status request-success text-success\" style=\"\"></span>\r\n				<span class=\"request-status request-error text-danger\" style=\"\"></span>\r\n     		</div>\r\n     		\r\n      	</div>\r\n      	\r\n      	<div class=\"on-success text-center\" style=\"display: none;\">\r\n      	\r\n      		<p>Request to reset password was successfully received.<br>\r\n            A link to reset the password will be sent shortly, if that email address is currently active in our system.</p>\r\n      		\r\n      	</div>\r\n      	\r\n      </div>\r\n      <div class=\"modal-footer\">\r\n      \r\n      	<div class=\"initial\">\r\n	      	<div class=\"initial text-center\">\r\n		        <button id=\"email-reset-button\" class=\"btn btn-info modal-active\" role=\"button\">Reset</button>\r\n	      	</div>\r\n      	</div>\r\n      	\r\n      	<div class=\"on-success text-center\" style=\"display: none;\">\r\n      	\r\n			<button class=\"close-modal btn btn-info\">Close</button>\r\n			\r\n      	</div>\r\n      	\r\n      </div>\r\n    </div>\r\n<!-- \r\n  </div>\r\n</div>       \r\n -->";
},"useData":true});

this["JST"]["templates/signup-iframe.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "\r\n<div class=\"modal fade\" id=\"signup-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"signup-modal-label\" aria-hidden=\"true\">\r\n  <div class=\"modal-dialog\" role=\"document\">\r\n    <div class=\"modal-content\">\r\n      <div class=\"modal-header\">\r\n        <button type=\"button\" class=\"close close-modal\" aria-label=\"Close\"><!-- data-dismiss=\"modal\" -->\r\n          <span aria-hidden=\"true\">&times;</span>\r\n        </button>\r\n       <br />\r\n      </div>\r\n      <div class=\"modal-body\">\r\n      	<iframe class=\"popover-iframe\"></iframe>\r\n      </div>\r\n    </div>\r\n  </div>\r\n</div>      ";
},"useData":true});

this["JST"]["templates/signup-modal.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!-- \r\n<div class=\"modal fade\" id=\"signup-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"signup-modal-label\" aria-hidden=\"true\">\r\n  <div class=\"modal-dialog\" role=\"document\">\r\n  -->\r\n    <div class=\"modal-content-x\" id=\"signup-modal\">\r\n<!-- \r\n      <div class=\"modal-header\">\r\n        <button type=\"button\" class=\"close close-modal\" aria-label=\"Close\">\r\n          <span aria-hidden=\"true\">&times;</span>\r\n        </button>\r\n       <br />\r\n      </div>\r\n -->    \r\n      <div class=\"modal-body\">\r\n	        <p>Invitation Code:</p>\r\n	     <div class=\"form-group invitation-row\">\r\n	       <input type=\"text\" class=\"form-control signup-active\" placeholder=\"Invitation Code\" id=\"signup-invitation-code\" value=\"\" />\r\n	       <i class=\"fa fa-user\"></i>\r\n	       <br />\r\n	       <span>Don't have a code ? <a href=\"/requestinvitationcode\" data-navigo2>Join our waiting list</a></span>\r\n	     </div>\r\n	        <p>Customer ID:</p>\r\n	     <div class=\"form-group\">\r\n	       <input type=\"text\" class=\"form-control signup-active\" placeholder=\"ID\" id=\"signup-customer-id\" />\r\n	       <i class=\"fa fa-user\"></i>\r\n	     </div>\r\n	          <h6>Choose a unique identifier for your account.</h6><br />\r\n	    	<p>Name:</p>\r\n	     <div class=\"form-group\">\r\n	       <input type=\"text\" class=\"form-control signup-active\" placeholder=\"Name\" id=\"signup-name\" />\r\n	       <i class=\"fa fa-user\"></i>\r\n	     </div>\r\n	        <p>Email:</p>\r\n	     <div class=\"form-group\">\r\n	       <input type=\"text\" class=\"form-control signup-active\" placeholder=\"Email\" id=\"signup-email\" />\r\n	       <i class=\"fa fa-user\"></i>\r\n	     </div>\r\n	        <p>Password:</p>\r\n	     <div class=\"form-group log-status\">\r\n	       <input type=\"password\" class=\"form-control signup-active\" placeholder=\"Password\" id=\"signup-password\" />\r\n	       <i class=\"fa fa-lock\"></i>\r\n	     </div>\r\n	       <p>Repeat Password:</p>\r\n	     <div class=\"form-group log-status\">\r\n	       <input type=\"password\" class=\"form-control signup-active\" placeholder=\"Repeat Password\" id=\"signup-password-repeat\" />\r\n	       <i class=\"fa fa-lock\"></i>\r\n	     </div>\r\n	     \r\n	     <div>&nbsp;\r\n			<span class=\"signup-status signup-error text-danger\"></span>\r\n			<span class=\"signup-status signup-success text-success\"></span>\r\n	     </div>\r\n	     \r\n      </div>\r\n      <div class=\"modal-footer\">\r\n        <div class=\"text-center\">\r\n        	<button id=\"signup-confirm-button\" class=\"btn btn-info signup-active\">Sign Up</button>\r\n        </div>\r\n      </div>\r\n    </div>\r\n<!-- \r\n  </div>\r\n</div>      \r\n -->";
},"useData":true});

this["JST"]["templates/unlock-login-iframe.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "\n<div class=\"modal fade\" id=\"unlock-login-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"unlock-login-modal-label\" aria-hidden=\"true\">\n  <div class=\"modal-dialog\" role=\"document\">\n    <div class=\"modal-content\">\n      <div class=\"modal-header\">\n        <button type=\"button\" class=\"close close-modal\" aria-label=\"Close\">\n          <span aria-hidden=\"true\">&times;</span>\n        </button>\n       <br>\n      </div>\n	  <div class=\"modal-body\">\n      	<iframe class=\"popover-iframe\"></iframe>\n      </div>\n    </div>\n  </div>\n</div> ";
},"useData":true});

this["JST"]["templates/unlock-login-modal.hbs"] = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<!-- \n<div class=\"modal fade\" id=\"unlock-login-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"unlock-login-modal-label\" aria-hidden=\"true\">\n  <div class=\"modal-dialog\" role=\"document\">\n -->\n    <div class=\"modal-content-x\" id=\"unlock-login-modal\">\n      <!--\n      <div class=\"modal-header\">\n        <button type=\"button\" class=\"close close-modal\" aria-label=\"Close\">\n          <span aria-hidden=\"true\">&times;</span>\n        </button>\n       <br>\n      </div>\n      -->\n      <div class=\"modal-body\">\n      \n      	<div class=\"initial\">\n      \n            <p>Request unlocking your Chat.AI login email:</p>\n            \n        	<p>Email Address:</p>\n     		<div class=\"form-group \">\n       			<input type=\"email\" class=\"form-control modal-active\" placeholder=\"Email \" id=\"unlock-input-email\">\n       			<i class=\"fa fa-user\"></i>\n     		</div>\n     		\n     		<div>&nbsp;\n				<span class=\"request-status request-success text-success\" style=\"\"></span>\n				<span class=\"request-status request-error text-danger\" style=\"\"></span>\n     		</div>\n     		\n      	</div>\n      	\n      	<div class=\"on-success text-center\" style=\"display: none;\">\n      	\n      		<p>Request to unlock your login was successfully received.<br>\n            A link to unlock the login email address will be sent shortly, if that email address is currently active in our system.</p>\n      		\n      	</div>\n      	\n      </div>\n      <div class=\"modal-footer\">\n      \n      	<div class=\"initial\">\n	      	<div class=\"initial text-center\">\n		        <button id=\"email-unlock-button\" class=\"btn btn-info modal-active\" role=\"button\">Request Unlock</button>\n	      	</div>\n      	</div>\n      	\n      	<div class=\"on-success text-center\" style=\"display: none;\">\n      	\n			<button class=\"close-modal btn btn-info\">Close</button>\n			\n      	</div>\n      	\n      </div>\n    </div>\n<!-- \n  </div>\n</div>       \n -->";
},"useData":true});